name: ✅ checks

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      library:
        required: true
        type: string
      coverage:
        default: true
        type: boolean
      fail_on_coverage:
        default: false
        type: boolean
      coverage_threshold:
        default: '40 80'
        type: string
      source_dir:
        default: 'include/'
        type: string

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    with:
      library: ${{ inputs.library }}
      coverage: ${{ inputs.coverage }}
      fail_on_coverage: ${{ inputs.fail_on_coverage }}
      coverage_threshold: ${{ inputs.coverage_threshold }}
    secrets: inherit

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      library: ${{ inputs.library }}
      source_dir: ${{ inputs.source_dir }}
    secrets: inherit

  docs:
    uses: ./.github/workflows/docs.yml
    with:
      library: ${{ inputs.library }}
      source_dir: ${{ inputs.source_dir }}
    secrets: inherit

  publish_artifacts:
    needs: [ lint, docs, tests ]
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/download-artifact@master
        with:
          name: docs
          path: docs/

      - uses: actions/download-artifact@master
        with:
          name: coverage
          path: docs/coverage

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/'

      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  deploy_package:
    needs: [ lint, docs, tests ]
    uses: ./.github/workflows/deploy.yml
    with:
      library: ${{ inputs.library }}
    secrets: inherit
