name: ✅ CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 0'

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    with:
      library: libhal
      coverage: true
    secrets: inherit
