name: 🚀 deploy

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      library:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: 📥 Install CMake & Conan
        run: pip install cmake conan==2.0.0

      - name: 📡 Add `libhal-trunk` conan remote
        run: |
             conan remote add libhal-trunk \
             https://libhal.jfrog.io/artifactory/api/conan/trunk-conan

      - name: 📡 Create and setup default profile
        run: conan profile detect --force

      - name: 👁️‍🗨️ Show conan profile
        run: conan profile show

      - name: 📦 Create Conan Package & Verify Test Package
        run: conan create . --build=missing -s compiler.version=11 -s compiler.cppstd=20 -s compiler=gcc -s compiler.libcxx=libstdc++ -s:b compiler.cppstd=20 -s:b compiler=gcc -s:b compiler.version=11 -s:b compiler.libcxx=libstdc++

      - name: 📡 Sign into JFrog Artifactory
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          API_KEY: ${{ secrets.JFROG_LIBHAL_TRUNK_API_KEY }}
          JFROG_USER: ${{ secrets.JFROG_LIBHAL_TRUNK_USER }}
        run: conan remote login -p $API_KEY libhal-trunk $JFROG_USER

      - name: 🆙 Upload package to `libhal-trunk` repo
        if: ${{ github.ref == 'refs/heads/main' }}
        run: conan upload "${{ inputs.library }}/*" --confirm -r=libhal-trunk
