name: 📖 docs

on:
  workflow_call:
    inputs:
      library:
        required: true
        type: string
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 0'

jobs:
  docs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Copy README.md to docs directory
        run: cp README.md logo.svg docs

      - name: Copy logo.svg to docs directory
        run: cp logo.svg docs/

      - name: Apply repo name to 'doxygen.conf' project name
        working-directory: docs
        run: echo PROJECT_NAME = ${{ github.event.repository.name }} >> doxygen.conf

      - name: 📖 Run Doxygen
        uses: mattnotmitt/doxygen-action@v1
        with:
            working-directory: docs
            doxyfile-path: 'doxygen.conf'

      - name: ⚠️ Read out any doxygen warnings
        if: always()
        working-directory: docs
        run: cat doxygen_warn.log

      - name: 🚀 Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/
          enable_jekyll: true
