name: 📖 docs

on:
  workflow_call:
    inputs:
      library:
        required: true
        type: string
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 0'

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: 📥 Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: 📥 Download doxybook2
        run: wget https://github.com/matusnovak/doxybook2/releases/download/v1.4.0/doxybook2-linux-amd64-v1.4.0.zip

      - name: 📤 Extract doxybook2
        run: unzip doxybook2-linux-amd64-v1.4.0.zip -d doxybook2

      - name: 📖 Run Doxygen
        uses: mattnotmitt/doxygen-action@v1
        with:
            working-directory: docs
            doxyfile-path: 'doxygen.conf'

      - name: ⚠️ Read out any doxygen warnings
        if: always()
        working-directory: docs
        run: cat doxygen_warn.log

      - name: 📚 Run doxybook2
        working-directory: docs
        run: ../doxybook2/bin/doxybook2 --input doxygen/xml --output content/api --config doxybook2/config.json  --templates doxybook2

      - name: 🔨 Build Doc Website
        working-directory: docs
        run: hugo --minify

      - name: 🚀 Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/public
