name: 📝 docs

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      library:
        required: true
        type: string
      source_dir: # Not used currently
        required: true
        type: string

jobs:
  docs:
    runs-on: ubuntu-22.04
    environment: Production
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Apply repo name to 'doxygen.conf' project name
        working-directory: docs
        run: echo PROJECT_NAME = ${{ github.event.repository.name }} >> doxygen.conf

      - name: 📖 Run Doxygen
        uses: mattnotmitt/doxygen-action@v1
        with:
            working-directory: docs
            doxyfile-path: 'doxygen.conf'

      - name: ⚠️ Read out any doxygen warnings
        if: always()
        working-directory: docs
        run: cat doxygen_warn.log

      - uses: actions/upload-artifact@master
        with:
          name: docs
          path: docs/
