name: tests

on:
  workflow_call:
    inputs:
      library:
        required: true
        type: string
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 0'

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install CMake
        run: pip install cmake

      - name: Install conan
        run: pip install conan

      - name: Install g++-10
        run: sudo apt install g++-10

      - name: Install Conan Package & Run Unit Tests
        run: conan create .
